Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false
Lint/Syntax:
  Enabled: false
Style/FrozenStringLiteralComment:
  EnforcedStyle: never
Style/GlobalVars:
  Enabled: false

AllCops:
  Exclude:
    - "Guardfile"
    - "Rakefile"
  DisplayCopNames: true



Metrics/MethodLength:
  Max: 30
Metrics/AbcSize:
  Max: 50
Metrics/PerceivedComplexity:
  Max: 150
Metrics/CyclomaticComplexity:
  Max: 150
Metrics/ClassLength:
  Max: 150


Style/ClassAndModuleChildren:
  Enabled: false
Style/EachForSimpleLoop:
  Enabled: false
Style/AndOr:
  Enabled: false
Style/DefWithParentheses:
  Enabled: false

Layout/HashAlignment:
  EnforcedColonStyle: key
Layout/ExtraSpacing:
  AllowForAlignment: false
Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented
Lint/RaiseException:
  Enabled: false
Lint/StructNewOverride:
  Enabled: false
Style/HashEachMethods:
  Enabled: false
Style/HashTransformKeys:
  Enabled: false
Style/HashTransformValues:
  Enabled: false
Style/MultipleComparison:
  Enabled: false
Metrics/BlockNesting:
  Enabled: false
Style/Next:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/UnlessElse:
  Enabled: false
Style/BlockComments:
  Enabled: false

